/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/members": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.members.id"];
          updated_at?: parameters["rowFilter.members.updated_at"];
          full_name?: parameters["rowFilter.members.full_name"];
          avatar_url?: parameters["rowFilter.members.avatar_url"];
          linkedin?: parameters["rowFilter.members.linkedin"];
          year?: parameters["rowFilter.members.year"];
          city?: parameters["rowFilter.members.city"];
          bio?: parameters["rowFilter.members.bio"];
          current_occupation?: parameters["rowFilter.members.current_occupation"];
          place_of_occupation?: parameters["rowFilter.members.place_of_occupation"];
          onboarded?: parameters["rowFilter.members.onboarded"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["members"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** members */
          members?: definitions["members"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.members.id"];
          updated_at?: parameters["rowFilter.members.updated_at"];
          full_name?: parameters["rowFilter.members.full_name"];
          avatar_url?: parameters["rowFilter.members.avatar_url"];
          linkedin?: parameters["rowFilter.members.linkedin"];
          year?: parameters["rowFilter.members.year"];
          city?: parameters["rowFilter.members.city"];
          bio?: parameters["rowFilter.members.bio"];
          current_occupation?: parameters["rowFilter.members.current_occupation"];
          place_of_occupation?: parameters["rowFilter.members.place_of_occupation"];
          onboarded?: parameters["rowFilter.members.onboarded"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.members.id"];
          updated_at?: parameters["rowFilter.members.updated_at"];
          full_name?: parameters["rowFilter.members.full_name"];
          avatar_url?: parameters["rowFilter.members.avatar_url"];
          linkedin?: parameters["rowFilter.members.linkedin"];
          year?: parameters["rowFilter.members.year"];
          city?: parameters["rowFilter.members.city"];
          bio?: parameters["rowFilter.members.bio"];
          current_occupation?: parameters["rowFilter.members.current_occupation"];
          place_of_occupation?: parameters["rowFilter.members.place_of_occupation"];
          onboarded?: parameters["rowFilter.members.onboarded"];
        };
        body: {
          /** members */
          members?: definitions["members"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  members: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    updated_at?: string;
    full_name: string;
    avatar_url?: string;
    linkedin?: string;
    year: string;
    city: string;
    bio?: string;
    current_occupation?: string;
    place_of_occupation?: string;
    onboarded?: boolean;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** members */
  "body.members": definitions["members"];
  "rowFilter.members.id": string;
  "rowFilter.members.updated_at": string;
  "rowFilter.members.full_name": string;
  "rowFilter.members.avatar_url": string;
  "rowFilter.members.linkedin": string;
  "rowFilter.members.year": string;
  "rowFilter.members.city": string;
  "rowFilter.members.bio": string;
  "rowFilter.members.current_occupation": string;
  "rowFilter.members.place_of_occupation": string;
  "rowFilter.members.onboarded": string;
}

export interface operations {}

export interface external {}
